name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
projects: ["voice-mcp/1"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure setting '...'
        3. Use feature '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs and Error Messages
      description: If applicable, add logs or error messages
      render: text
      placeholder: Paste logs here...

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - "Low - Minor inconvenience"
        - "Medium - Affects functionality but has workaround"
        - "High - Major functionality broken"
        - "Critical - Application unusable"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Component
      description: Which component is affected?
      options:
        - "TTS (Text-to-Speech)"
        - "STT (Speech-to-Text)"
        - "Hotkey System"
        - "Audio Processing"
        - "Configuration"
        - "MCP Server"
        - "CLI"
        - "Documentation"
        - "Tests"
        - "Build/CI"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: |
        Please provide information about your environment.
        Tip: You can get this by running `uv run python -c "import voice_mcp; print(voice_mcp.__version__)"`
      value: |
        - **OS**: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - **Python Version**: [e.g., 3.11.5]
        - **Voice MCP Version**: [e.g., 0.1.0]
        - **Audio System**: [e.g., PulseAudio, WASAPI, CoreAudio]
        - **Hardware**: [e.g., Built-in microphone, USB headset]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Configuration
      description: Relevant configuration (remove sensitive information)
      render: bash
      placeholder: |
        VOICE_MCP_LOG_LEVEL=INFO
        VOICE_MCP_TTS_MODEL=tts_models/en/ljspeech/tacotron2-DDC
        VOICE_MCP_STT_MODEL=base
        # etc...

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all relevant information
          required: true
        - label: I have tested with the latest version
          required: true
        - label: I have removed any sensitive information from logs/config
          required: true
